### ISSUE TITLE
Allow to chose the variability percentage when computing balancing

### ISSUE THREAD

**Issue by ale93p** [ale93p/namb#103]
#### Issue Description ####

When computing the  `parallelism` and `workload` balancing values for the tasks, the application use a hardcoded variability percentage. This percentage should be added in the configuration, allowing the user to define it.

#### Proposed Solution (if you have any) ####

Example in configuration file:
```yaml
dataflow:
    workload:
        variability: 0.5  # 1 is 100%
```
