### ISSUE TITLE
Implement windowing

### ISSUE THREAD

**Issue by ale93p** [ale93p/namb#107]
#### Issue Description ####

Add windowing in:
- [x] Storm
- [x] Heron
- [x] Flink

#### Proposed Solution (if you have any) ####

Add to the configurations:
```yaml
dataflow:
    windowing:
        enable: yes | no
        period: 10 # seconds
```
