### ISSUE TITLE
Rename balancing in data properties

### ISSUE THREAD

**Issue by ale93p** [ale93p/namb#108]
#### Issue Description ####
 
Rename the balancing property under data section, to better describe its behaviour.

#### Proposed Solution (if you have any) ####

```yaml
datastream:
    synthetic:
        data:
            distribution: uniform | variable
```
