### ISSUE TITLE
Configuration: Fix synthetic DataStream parameters

### ISSUE THREAD

**Issue by ale93p** [ale93p/namb#51]
- [x] Remove data type (see #45)
- [x] create new arrival group
- [x] add data heterogeneity

Final example:
```
synthetic:
  data:
    size: <val>
    hetereogeneity: <val>
    decrease: <val>
  flow:
    distribution: <val>
    rate: <val>
```
