### ISSUE TITLE
Feature: Add external data source (Kafka)

### ISSUE THREAD

**Issue by ale93p** [ale93p/namb#78]
Implement an external data source, making able to test custom input flows. In order to do so it is necessary:
- [ ] Add External Kafka `datastream` section in configuraiton. It should look something like:
```
kafka:
  host: 127.0.0.1
  port: 1234
  topic: test_topic
```
- [ ] Implement an external DataSource in the Benchmark application (e.g. `KafkaSpout` in Storm)
